name: my_softball_team
description: A new Flutter application to track your softball team&#x27;s players and games.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth: "^0.5.11"
  cloud_firestore: "^0.7.3"
  shared_preferences: "^0.4.2"
  groovin_material_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  fonts:
    - family: sourcesanspro
      fonts:
        - asset: fonts/sourcesanspro_regular.ttf
    - family: materialdesignicons
      fonts:
        - asset: fonts/materialdesignicons-webfont.ttf

