name: my_softball_team
description: A new Flutter application to track your softball team&#x27;s players and games.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.6.2+1
  cloud_firestore: "^0.7.3"
  shared_preferences: "^0.4.2"
  groovin_material_icons: ^1.1.2
  outline_material_icons: ^0.1.0
  package_info: ^0.3.2
  url_launcher: ^3.0.3
  flutter_email_sender:
    path: C:\Users\groov\Flutter_Projects\flutter_email_sender
    #path: C:\Users\Reuvain\Flutter Projects\flutter_email_sender
  rounded_modal: ^1.0.0
  datetime_picker_formfield: ^0.1.6
  groovin_widgets: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.6.1"

flutter_icons:
  android: true
  image_path: "assets/icon2.png"

flutter:

  uses-material-design: true
  fonts:
    - family: sourcesanspro
      fonts:
        - asset: fonts/sourcesanspro_regular.ttf
    - family: materialdesignicons
      fonts:
        - asset: fonts/materialdesignicons-webfont.ttf

